version: '3'

services:
  bookings:
    image: selenium/standalone-chrome:4.4.0-20220831
    container_name: new_bookings
    ports: 
    - 4444:4444
    - 7900:7900
    volumes:
     - ./Scraper/app/downloads:/home/seluser/Downloads
    restart: always

  scraper:
    image: grandwelcome/app:1.0.0
    container_name: scraper
    volumes:
     - ./Scraper/app:/app
    command: sh -c "python3 newbookings.py"
    depends_on:
     - bookings 

  dashboard:
    image: grandwelcome/dashboard:1.0.0
    container_name: dashboard
    ports:
    - 8501:8501
    volumes:
     - ./Dashboard/app:/app
     - ./Scraper/app/configs:/app/configs
     - ./Scraper/app/reports:/app/reports

